# Generated by Django 5.1.3 on 2024-11-19 01:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=30)),
                ('tag_description', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'ordering': ['tag_name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_nickname', models.CharField(max_length=30)),
                ('user_full_name', models.CharField(max_length=70)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_registration_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['user_registration_date'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=70)),
                ('post_description', models.CharField(max_length=300)),
                ('post_slug', models.SlugField(max_length=40)),
                ('post_pinned', models.BooleanField(default=False)),
                ('post_status', models.CharField(choices=[('recent', 'Recent'), ('edited', 'Edited'), ('old', 'Old')], default='recent', max_length=6)),
                ('post_karma', models.IntegerField(default=0)),
                ('post_date', models.DateField(default=django.utils.timezone.now)),
                ('post_modified_date', models.DateField(blank=True, null=True)),
                ('post_content', models.TextField()),
                ('post_parent', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.post')),
                ('post_tags', models.ManyToManyField(to='app.tag')),
                ('post_author', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.user')),
            ],
            options={
                'ordering': ['post_title'],
            },
        ),
    ]
