# Generated by Django 5.1.3 on 2024-11-24 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_picture_id',
            field=models.CharField(blank=True, default='mendoza-argentina', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_tags',
            field=models.ManyToManyField(blank=True, null=True, to='app.tag'),
        ),
    ]
